config/routes.rb
Rails.application.routes.draw do
  resources :notes
  patch 'drag/note'
  root 'notes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  has_one_attached :kitty_pic do |attachable|
    attachable.variant :thumb, resize_to_fill: [150, 150]
  end
  acts_as_list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drag_controller.rb
class DragController < ApplicationController
  def note
    @note = Note.find(drag_note_params[:id])
    @note.insert_at(drag_note_params[:position].to_i + 1)
  end

  private

  def drag_note_params
    params.require(:resource).permit(:id, :position)
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[show edit update destroy]

  def index
    @admin = true
    # @admin = false
    @notes = Note.all.order(position: :asc)
  end

  def show; end

  def new
    @note = Note.new
  end

  def edit; end

  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to note_url(@note), notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to note_url(@note), notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @note.destroy

    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:name, :kitty_pic)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drag_helper.rb
module DragHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Drag</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,300;0,400;0,900;1,900&display=swap" rel="stylesheet">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div class="done-btn">
    <%= image_tag 'kitty.svg'%>
      <h3>Done?</h3>
      <div class="relative">
        <h5>Save & Compare with everyone else!</h5>
      </div>
    </div>
    <%= yield %>
  </body>
</html>

app/views/notes/_draggable.html.erb
<% dragActions = "  dragstart->drag#dragStart 
                    dragover->drag#dragOver
                    dragenter->drag#dragEnter
                    drop->drag#drop
                    dragend->drag#dragEnd" %>

<%= content_tag :div,
    class: "icon draggable",
    draggable: true,
    data: {
        controller: "drag",
        action: dragActions,
        resource_id: note.id,
        url: "drag/note",
        parent: "notes"
    } do %>
        <%= render note %>
<% end %>

app/views/notes/_form.html.erb
<%= form_with(model: note) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  
  <div>
    <%= form.file_field :kitty_pic %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>" class="note">
  <div class="wrapper">

    <h2 class="front"><%= note.name %></h2>
    <%= image_tag note.kitty_pic.variant(:thumb) %>
    <h2 class="back"><%= note.name %></h2>
    <div class="spacer"></div>
  </div>
</div>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Show this note", @note %> |
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container wide-box notes">
  <h1 class="flex">Kitties</h1>

  <div id="notes" class="padding">
    <% @notes.each do |note| %>
      <% if @admin then %>
        <%= render 'notes/draggable', note: note %>
      <% else %>
        <%= render note %>
      <% end %>
    <% end %>
  </div>


</div>

app/views/notes/new.html.erb
<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @note %>

<div>
  <%= link_to "Edit this note", edit_note_path(@note) %> |
  <%= link_to "Back to notes", notes_path %>

  <%= button_to "Destroy this note", @note, method: :delete %>
</div>